"""
    You are given two strings s and t.

    String t is generated by random shuffling string s and then add one more letter at a random position.
    Return the letter that was added to t.
"""

class Solution:
    # Easy
    def findTheDifference(self, s: str, t: str) -> str:
        for el in s:
            s = s.replace(el, "", 1)
            t = t.replace(el, "", 1)
        return s if s else t